// 📁 AUTHENTICATION 📁
### Autenticando usuario
POST http://localhost:3000/api/auth/signin
Content-Type: application/json

{
	"email": "admin@gmail.com",
	"password": "admin"
}

### Creando usuario
POST http://localhost:3000/api/auth/signup
Content-Type: application/json
    
{
    "username": "admin",
    "email": "admin@gmail.com",
    "password": "admin"
}

// 📁 USER 📁
### Actualizar usuario
Put http://localhost:3000/api/user/update/65d7b15612b48787920ab659
Content-Type: application/json

{
	"username": "admin000",
    "email": "admin000@gmail.com",
    "password": "admin000"
}

###  Eliminar usuario
DELETE http://localhost:3000/api/user/delete/65d55f4ced0035776a705feb



// 📁 POST 📁
### Crear post
POST http://localhost:3000/api/post/create
content-Content-Type: application/json

{
    "title": "new post",
    "content": "post content"
}

### Obtener todos los posts
GET POST http://localhost:3000/api/post/getposts
