// 📁 USER 📁
### Actualizar usuario
Put http://localhost:3000/api/user/update/65d74542c50e7dda4556e5c1
Content-Type: application/json

{
	"username": "prude"
}

### Eliminar usuario
DELETE http://localhost:3000/api/user/delete/65d55f4ced0035776a705feb

// 📁 AUTHENTICATION 📁
### Autenticando usuario
POST http://localhost:3000/api/auth/signin
Content-Type: application/json

{
	"email": "admin@gmail.com",
	"password": "admin"
}

### Creando usuario
POST http://localhost:3000/api/auth/signup
Content-Type: application/json
    
{
    "username": "admin",
    "email": "admin@gmail.com",
    "password": "admin"
}

// 📁 POST 📁
### Crear post
POST http://localhost:3000/api/post/create
content-Content-Type: application/json

{
    "title": "new post",
    "content": "post content"
}
